2023-01-06 12:43:05,987 ERROR: Exception on /auth/logout [GET] [in /home/anith/Desktop/Djangoproject/flask_microblog/venv/lib/python3.8/site-packages/flask/app.py:1741]
Traceback (most recent call last):
  File "/home/anith/Desktop/Djangoproject/flask_microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/anith/Desktop/Djangoproject/flask_microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/anith/Desktop/Djangoproject/flask_microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/anith/Desktop/Djangoproject/flask_microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/anith/Desktop/Djangoproject/flask_microblog/app/auth/routes.py", line 32, in logout
    return redirect(url_for('index'))
  File "/home/anith/Desktop/Djangoproject/flask_microblog/venv/lib/python3.8/site-packages/flask/helpers.py", line 256, in url_for
    return current_app.url_for(
  File "/home/anith/Desktop/Djangoproject/flask_microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2031, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "/home/anith/Desktop/Djangoproject/flask_microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2020, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "/home/anith/Desktop/Djangoproject/flask_microblog/venv/lib/python3.8/site-packages/werkzeug/routing/map.py", line 917, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'index'. Did you mean 'main.index' instead?
2023-01-06 12:45:21,478 INFO: Microblog startup [in /home/anith/Desktop/Djangoproject/flask_microblog/app/__init__.py:72]
2023-01-06 12:52:35,322 INFO: Microblog startup [in /home/anith/Desktop/Djangoproject/flask_microblog/app/__init__.py:72]
2023-01-09 11:47:09,218 INFO: Microblog startup [in /home/anith/Desktop/Djangoproject/flask_microblog/app/__init__.py:72]
2023-01-09 11:47:26,597 INFO: Microblog startup [in /home/anith/Desktop/Djangoproject/flask_microblog/app/__init__.py:72]
2023-01-09 12:17:21,352 INFO: Microblog startup [in /home/anith/Desktop/Djangoproject/flask_microblog/app/__init__.py:72]
2023-01-09 12:17:29,450 INFO: Microblog startup [in /home/anith/Desktop/Djangoproject/flask_microblog/app/__init__.py:72]
2023-01-09 12:29:35,811 INFO: Microblog startup [in /home/anith/Desktop/Djangoproject/flask_microblog/app/__init__.py:72]
2023-01-09 12:32:39,879 INFO: Microblog startup [in /home/anith/Desktop/Djangoproject/flask_microblog/app/__init__.py:72]
2023-01-09 12:33:07,186 ERROR: Exception on /send_message/susan [GET] [in /home/anith/Desktop/Djangoproject/flask_microblog/venv/lib/python3.8/site-packages/flask/app.py:1741]
Traceback (most recent call last):
  File "/home/anith/Desktop/Djangoproject/flask_microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/anith/Desktop/Djangoproject/flask_microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/anith/Desktop/Djangoproject/flask_microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/anith/Desktop/Djangoproject/flask_microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/anith/Desktop/Djangoproject/flask_microblog/venv/lib/python3.8/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/anith/Desktop/Djangoproject/flask_microblog/app/main/routes.py", line 142, in send_message
    return render_template('send_message.html', title='Send Message',
  File "/home/anith/Desktop/Djangoproject/flask_microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 146, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/home/anith/Desktop/Djangoproject/flask_microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/anith/Desktop/Djangoproject/flask_microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/anith/Desktop/Djangoproject/flask_microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/anith/Desktop/Djangoproject/flask_microblog/venv/lib/python3.8/site-packages/jinja2/loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "/home/anith/Desktop/Djangoproject/flask_microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/home/anith/Desktop/Djangoproject/flask_microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/anith/Desktop/Djangoproject/flask_microblog/app/templates/send_message.html", line 5, in template
    <h1>{{ 'Send Message to %(recipient)s', recipient=recipient }}</h1>
jinja2.exceptions.TemplateSyntaxError: expected token 'end of print statement', got '='
2023-01-09 12:46:08,051 INFO: Microblog startup [in /home/anith/Desktop/Djangoproject/flask_microblog/app/__init__.py:72]
2023-01-09 12:46:16,695 ERROR: Exception on /send_message/susan [GET] [in /home/anith/Desktop/Djangoproject/flask_microblog/venv/lib/python3.8/site-packages/flask/app.py:1741]
Traceback (most recent call last):
  File "/home/anith/Desktop/Djangoproject/flask_microblog/venv/lib/python3.8/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/anith/Desktop/Djangoproject/flask_microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/anith/Desktop/Djangoproject/flask_microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/anith/Desktop/Djangoproject/flask_microblog/venv/lib/python3.8/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/anith/Desktop/Djangoproject/flask_microblog/venv/lib/python3.8/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/home/anith/Desktop/Djangoproject/flask_microblog/app/main/routes.py", line 142, in send_message
    return render_template('send_message.html', title='Send Message',
  File "/home/anith/Desktop/Djangoproject/flask_microblog/venv/lib/python3.8/site-packages/flask/templating.py", line 146, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "/home/anith/Desktop/Djangoproject/flask_microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/anith/Desktop/Djangoproject/flask_microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/anith/Desktop/Djangoproject/flask_microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/anith/Desktop/Djangoproject/flask_microblog/venv/lib/python3.8/site-packages/jinja2/loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "/home/anith/Desktop/Djangoproject/flask_microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/home/anith/Desktop/Djangoproject/flask_microblog/venv/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/anith/Desktop/Djangoproject/flask_microblog/app/templates/send_message.html", line 5, in template
    <h1>{{ ('Send Message to %(recipient)s', recipient=recipient) }}</h1>
jinja2.exceptions.TemplateSyntaxError: expected token ')', got '='
2023-01-09 12:48:45,053 INFO: Microblog startup [in /home/anith/Desktop/Djangoproject/flask_microblog/app/__init__.py:72]
2023-01-09 15:12:36,704 INFO: Microblog startup [in /home/anith/Desktop/Djangoproject/flask_microblog/app/__init__.py:75]
